
services:
  localstack:
    image: localstack/localstack:3.8
    container_name: aws-local
    ports:
      - "4566:4566"

    environment:
      - SERVICES=s3,iam,lambda,dynamodb
      - AWS_DEFAULT_REGION=us-east-1

    volumes:
      - localstack:/var/lib/localstack
      - /var/run/docker.sock:/var/run/docker.sock

    networks:
      - app_network

  python-app:
    image: python:3.11-slim
    container_name: venv

    working_dir: /app

    ports:
      - "8888:8888"
      
    volumes:
      - ./:/app
      - pip_cache:/root/.cache/pip

    command: >
      sh -c "pip install  -r requirements.txt &&
              jupyter notebook --ip=0.0.0.0 --port=8888 --allow-root"

    depends_on:
      - localstack
    
    networks:
      - app_network

  postgres:
    image: postgres:16
    container_name: postgres

    env_file:
      - .env

    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

    ports:
      - "${DB_PORT}:5432"

    volumes:
      - postgres_db:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

    networks:
      - app_network

  dbt:
    image: ghcr.io/dbt-labs/dbt-postgres:1.9.latest
    container_name: dbt

    env_file:
      - .env

    volumes:
      - ./dbt:/usr/app/dbt

    working_dir: /usr/app/dbt

    depends_on:
      postgres:
        condition: service_healthy
    environment:
        DBT_PROFILES_DIR: /usr/app/dbt   
        DBT_PASSWORD: postgres
    tty: true

    entrypoint: ["/bin/bash", "-c"]

    command:
      - "tail -f /dev/null"


    networks:
      - app_network

volumes:
  postgres_db:
  localstack:
  pip_cache:



networks:
  app_network:
    driver: bridge